### ISSUE TITLE
Feature - jekyll placeholders

### ISSUE THREAD

**Issue by sjoyal** [sjoyal/sjoyal.github.io#39]
- [x] Researching including content for each post as opposed to a link to a page for each post?
  - [ ] use post title, body, etc with placeholders on main page? Can dynamic content be added to page so that journal entries open up like nested accordion? - review docs
  - [x] If not possible or if it requires bulldogging, reconfigure blog section for links to individual posts
  - [x] Style with Sass as appropriate

**Comment by sjoyal** [comment]
#37

**Comment by Terri5732** [comment]
sjoyal still here ?

**Comment by Terri5732** [comment]
I don't want to irritate or insult you by acknowledging I'm a work in progress, Need a Guide dog lol

**Comment by sjoyal** [comment]
#33
